#define PLUS 1
#define MINUS 2
#define MULT 3
#define DIVIDE 4
#define MODULO 5
#define EXP 6
#define LPAREN 7
#define RPAREN 8
#define LBRACKET 9
#define RBRACKET 10
#define EQUALS 11
#define LTHAN 12
#define RTHAN 13
#define COLON 14
#define COMMA 15
#define SCOLON 16
#define PERIOD 17
#define QUOTE 18
#define DQUOTE 19
#define NUMBER 20
#define IDENT 21
#define TAGIDENT 22
#define ENDTAGHEAD 23
